# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdoJobsQueue < Formula
  desc "ado-jobs-queue"
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cdalar/ado-jobs-queue/releases/download/v0.1.0/ado-jobs-queue-darwin-amd64.tar.gz"
      sha256 "a5acc0d53594fcbb5f281447d9e888985d014ea2bdb1e349d6931eccb4c7bcd6"

      def install
        bin.install "ado-jobs-queue"
      end
    end
    on_arm do
      url "https://github.com/cdalar/ado-jobs-queue/releases/download/v0.1.0/ado-jobs-queue-darwin-arm64.tar.gz"
      sha256 "3ce7023e45408e260cab740ba628319b6503ec5109980d2cddf326249b453b07"

      def install
        bin.install "ado-jobs-queue"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdalar/ado-jobs-queue/releases/download/v0.1.0/ado-jobs-queue-linux-amd64.tar.gz"
        sha256 "1be15d0986f5c2411be314bfab52bf8c063a4a2004109306562b9ba80faa87d7"

        def install
          bin.install "ado-jobs-queue"
        end
      end
    end
  end
end
