# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onctl < Formula
  desc "onctl"
  homepage ""
  version "0.1.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdalar/onctl/releases/download/v0.1.12/onctl-darwin-amd64.tar.gz"
      sha256 "9f3dff3cffadee72ab042449c7b25b263862a4f641719b49da2f3584c57b4a8b"

      def install
        bin.install "onctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdalar/onctl/releases/download/v0.1.12/onctl-darwin-arm64.tar.gz"
      sha256 "6fad91534f2fc484debdee1576ed9a22b3d2492f87e81796708446fc7c95cb5e"

      def install
        bin.install "onctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cdalar/onctl/releases/download/v0.1.12/onctl-linux-amd64.tar.gz"
      sha256 "21ec2a94415bb5cd5aa5f8195869f45e995a8fd62c51ea9d410e5c58ba2176e0"

      def install
        bin.install "onctl"
      end
    end
  end
end
