# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parampiper < Formula
  desc "parampiper"
  homepage ""
  version "0.0.5-alpha"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cdalar/parampiper/releases/download/v0.0.5-alpha/parampiper-darwin-arm64.tar.gz"
      sha256 "da698bc6c5a5222496580505f663e1e16aeaac095d2e4ef438012a0f98cddf80"

      def install
        bin.install "parampiper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdalar/parampiper/releases/download/v0.0.5-alpha/parampiper-darwin-amd64.tar.gz"
      sha256 "b709575749969f25eb48533cb3dc862862da01f62f8ef28129a7f7f018086d81"

      def install
        bin.install "parampiper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cdalar/parampiper/releases/download/v0.0.5-alpha/parampiper-linux-amd64.tar.gz"
      sha256 "7471e2a82928b0b178763474b9a0ef3fca5263dcf3e231dda485444ab27d60ba"

      def install
        bin.install "parampiper"
      end
    end
  end
end
