# This file was generated by GoReleaser. DO NOT EDIT.
cask "onctl" do
  version "0.1.26"

  on_macos do
    on_intel do
      sha256 "36426eabf217f67eda10163bb099ff6fac2b69d590dfb5f3879a7bf622a28923"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "19cbd3ff91d2e80ea2203de41d3f02617a1384ffde0e5002b5281adc97d97381"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "44d0d51104dd135b6214d20ad0cdd7305e8e39ee184eb3f2284cd95fea6f12f9"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "b605a71cca903823de99ea7e674f860e520896eef188d7a2a11972b654d5b9fa"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-linux-arm64.tar.gz"
    end
  end

  name "onctl"
  desc "onctl"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onctl"

  # No zap stanza required

end
