# This file was generated by GoReleaser. DO NOT EDIT.
cask "onctl" do
  version "0.1.27"

  on_macos do
    on_intel do
      sha256 "46dfee1c79de7f9333408d7553b11092ec7a7ddfe9a87f6d20f7c67165f18930"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "7a9552c5a1420c6e6f9dfb82dbd6ffd744181943146acf8fb49a6070c6c36bda"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5aeed0cffed6de6f0254a9a9a4b2c9ed4c0e825387ac5dee8d8d10ade3976abc"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "3bd505935ec25cb0d75332868111a4089155c04ab3345db13a2941d8a98f508c"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-linux-arm64.tar.gz"
    end
  end

  name "onctl"
  desc "onctl"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onctl"

  # No zap stanza required

end
