# This file was generated by GoReleaser. DO NOT EDIT.
cask "onctl" do
  version "0.1.31"

  on_macos do
    on_intel do
      sha256 "2d13f214df2bd396c3595da8b092b5a08a8d0270adf6a074a1047e33c0000d28"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "35795dfe8a08aa613235825b6173e6e814df79551e171c0707c0426737b6d666"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10561a93958bb77647c4c9dfd47c1c14c2ef79b846ca97634b9d8b59e2d833f8"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "df902f43b66aca14301d84eb70ad4d04459ade4ad91dbb10a8e3b3590feb9003"
      url "https://github.com/cdalar/onctl/releases/download/v#{version}/onctl-linux-arm64.tar.gz"
    end
  end

  name "onctl"
  desc "onctl"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onctl"

  # No zap stanza required

end
